spring.application.name=EmojiRaceBot

telegram.bot.username=${TELEGRAM_BOT_USERNAME:star_payment_fight_bot}
telegram.bot.token=${TELEGRAM_BOT_TOKEN:8556475803:AAHPsAly6OgzK071FxkCyV1yv9vJ2XWechY}

telegram.bot.channel.mainChannelChatId=${TELEGRAM_BOT_CHANNEL_MAINCHANNELCHATID:-1003778050363}
telegram.bot.channel.defaultDeleteMessageDelay=${TELEGRAM_BOT_CHANNEL_DEFAULTDELETEMESSAGEDELAY:15000}
telegram.bot.channel.defaultDeleteMessageMenuDelay=${TELEGRAM_BOT_CHANNEL_DEFAULTDELETEMESSAGEMENUDELAY:5000}
telegram.bot.channel.helpLink=${TELEGRAM_BOT_CHANNEL_HELPLINK:https://t.me/MiLLioNeR22222222222}
telegram.bot.channel.adminMode=${TELEGRAM_BOT_CHANNEL_ADMINMODE:true}
telegram.bot.race.defaultRaceSize=${TELEGRAM_BOT_RACE_DEFAULTRACESIZE:62.00}
telegram.bot.race.defaultBustSize=${TELEGRAM_BOT_RACE_DEFAULTBUSTSIZE:0.50}
telegram.bot.race.defaultSlowSize=${TELEGRAM_BOT_RACE_DEFAULTSLOWSIZE:0.75}
telegram.bot.race.defaultStepSize=${TELEGRAM_BOT_RACE_DEFAULTSTEPSIZE:2.00}
telegram.bot.race.replaceBustChance=${TELEGRAM_BOT_RACE_REPLACEBUSTCHANCE:75}
telegram.bot.race.equalizeBustChance=${TELEGRAM_BOT_RACE_EQUALIZEBUSTCHANCE:75}
telegram.bot.race.defaultRacerCount=${TELEGRAM_BOT_RACE_DEFAULTRACERCOUNT:4}
telegram.bot.race.generationIntervalMinutes=${TELEGRAM_BOT_RACE_GENERATIONINTERVALMINUTES:2}
telegram.bot.channel.botLink=${TELEGRAM_BOT_CHANNEL_BOTLINK:https://t.me/star_payment_fight_bot}
telegram.bot.channel.channelLink=${TELEGRAM_BOT_CHANNEL_CHANNELLINK:https://t.me/emoji_race/}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/emoji-race}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cuba}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cuba}
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}
spring.flyway.baseline-on-migrate=${SPRING_FLYWAY_BASELINE_ON_MIGRATE:true}

spring.sql.init.mode=always

telegram.bot.localTestModeEnabled=${TELEGRAM_BOT_LOCALTESTMODEENABLED:true}
telegram.bot.localTestModeUserId=${:740984236}
