CREATE TABLE IF NOT EXISTS BALANCE_TOPUPS (
    ID BIGSERIAL PRIMARY KEY,
    USER_CHAT_ID BIGINT NOT NULL,
    SUM BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    SOURCE VARCHAR(64) NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_BALANCE_TOPUPS_USER_CHAT_ID_CREATED_DATE
    ON BALANCE_TOPUPS (USER_CHAT_ID, CREATED_DATE DESC);
