CREATE SEQUENCE IF NOT EXISTS user_notifications_seq
    START WITH 1
    INCREMENT BY 50
    CACHE 50;

CREATE TABLE IF NOT EXISTS USER_NOTIFICATIONS (
    ID BIGINT PRIMARY KEY DEFAULT nextval('user_notifications_seq'),
    USER_CHAT_ID BIGINT NOT NULL,
    TEXT VARCHAR(2000) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_USER_NOTIFICATIONS_USER_CHAT_ID_CREATED_DATE
    ON USER_NOTIFICATIONS (USER_CHAT_ID, CREATED_DATE DESC);
