ALTER TABLE USERS
    ADD COLUMN IF NOT EXISTS PASSWORD_HASH VARCHAR(512);

ALTER TABLE USERS
    ADD COLUMN IF NOT EXISTS PASSWORD_SALT VARCHAR(255);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_USERS_USERNAME_LOWER
    ON USERS ((LOWER(USERNAME)))
    WHERE USERNAME IS NOT NULL;
