CREATE TABLE IF NOT EXISTS WEEKLY_PRIZE_LOGS (
    ID BIGSERIAL PRIMARY KEY,
    WEEK_START DATE NOT NULL UNIQUE,
    WINNER_USER_CHAT_ID BIGINT NOT NULL,
    PRIZE_STARS BIGINT NOT NULL,
    PRIZE_BOOSTERS INTEGER NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_WEEKLY_PRIZE_LOGS_WEEK_START
    ON WEEKLY_PRIZE_LOGS (WEEK_START);
