CREATE SEQUENCE IF NOT EXISTS weekly_prize_logs_seq START WITH 1 INCREMENT BY 50;

ALTER TABLE WEEKLY_PRIZE_LOGS
    ALTER COLUMN ID SET DEFAULT nextval('weekly_prize_logs_seq');

SELECT setval(
    'weekly_prize_logs_seq',
    GREATEST((SELECT COALESCE(MAX(ID), 0) FROM WEEKLY_PRIZE_LOGS), 1),
    (SELECT EXISTS(SELECT 1 FROM WEEKLY_PRIZE_LOGS))
);
