CREATE TABLE IF NOT EXISTS PLAYERS (
    NAME VARCHAR(255) PRIMARY KEY,
    WIN_COUNT BIGINT,
    MATCH_COUNT BIGINT
);

CREATE TABLE IF NOT EXISTS MATCHES (
    ID BIGSERIAL PRIMARY KEY,
    CREATED_DATE TIMESTAMP NOT NULL,
    TIMER_MESSAGE_ID INTEGER,
    WINNER_ID INTEGER,
    STATUS VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS USERS (
    ID UUID PRIMARY KEY,
    USER_CHAT_ID BIGINT NOT NULL,
    ACCOUNT_ID UUID UNIQUE,
    USERNAME VARCHAR(255),
    FAVORITE_PLAYER_ID VARCHAR(255),
    F_NAME VARCHAR(255),
    L_NAME VARCHAR(255),
    IS_ADMIN BOOLEAN
);

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ID UUID PRIMARY KEY,
    USER_CHAT_ID BIGINT NOT NULL,
    BALANCE BIGINT NOT NULL,
    USER_ID UUID UNIQUE,
    FREE_BUST_COUNT INTEGER
);

CREATE TABLE IF NOT EXISTS MATCH_PLAYERS (
    ID UUID PRIMARY KEY,
    PLAYER_NAME VARCHAR(255) NOT NULL,
    MATCH_ID BIGINT,
    NUMBER INTEGER NOT NULL,
    SCORE BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS PAYMENT_REQUESTS (
    ID UUID PRIMARY KEY,
    MATCH_PLAYER_ID UUID NOT NULL,
    USER_CHAT_ID BIGINT NOT NULL,
    SUM BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP,
    PAYED_DATE TIMESTAMP,
    STATUS VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS SCORE_MESSAGES (
    ID UUID PRIMARY KEY,
    CHAT_ID BIGINT NOT NULL,
    MESSAGE_ID BIGINT NOT NULL,
    MATCH_ID BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS JACKPOTS (
    ID BIGSERIAL PRIMARY KEY,
    CREATED_DATE TIMESTAMP NOT NULL,
    TIMER_MESSAGE_ID INTEGER,
    SUM BIGINT,
    WINNER_ID UUID,
    IS_PAYED BOOLEAN
);

ALTER TABLE USERS
    ADD CONSTRAINT FK_USERS_FAVORITE_PLAYER
        FOREIGN KEY (FAVORITE_PLAYER_ID) REFERENCES PLAYERS(NAME);

ALTER TABLE USERS
    ADD CONSTRAINT FK_USERS_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID);

ALTER TABLE ACCOUNTS
    ADD CONSTRAINT FK_ACCOUNTS_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

ALTER TABLE MATCH_PLAYERS
    ADD CONSTRAINT FK_MATCH_PLAYERS_PLAYER
        FOREIGN KEY (PLAYER_NAME) REFERENCES PLAYERS(NAME);

ALTER TABLE MATCH_PLAYERS
    ADD CONSTRAINT FK_MATCH_PLAYERS_MATCH
        FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(ID);

ALTER TABLE PAYMENT_REQUESTS
    ADD CONSTRAINT FK_PAYMENT_REQUESTS_MATCH_PLAYER
        FOREIGN KEY (MATCH_PLAYER_ID) REFERENCES MATCH_PLAYERS(ID);

ALTER TABLE SCORE_MESSAGES
    ADD CONSTRAINT FK_SCORE_MESSAGES_MATCH
        FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(ID);

ALTER TABLE JACKPOTS
    ADD CONSTRAINT FK_JACKPOTS_WINNER
        FOREIGN KEY (WINNER_ID) REFERENCES USERS(ID);

CREATE INDEX IF NOT EXISTS IDX_USERS_USER_CHAT_ID ON USERS (USER_CHAT_ID);
CREATE INDEX IF NOT EXISTS IDX_ACCOUNTS_USER_CHAT_ID ON ACCOUNTS (USER_CHAT_ID);
CREATE INDEX IF NOT EXISTS IDX_MATCHES_CREATED_DATE ON MATCHES (CREATED_DATE);
CREATE INDEX IF NOT EXISTS IDX_MATCH_PLAYERS_MATCH_ID ON MATCH_PLAYERS (MATCH_ID);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_REQUESTS_MATCH_PLAYER_STATUS
    ON PAYMENT_REQUESTS (MATCH_PLAYER_ID, STATUS);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_REQUESTS_USER_CHAT_ID ON PAYMENT_REQUESTS (USER_CHAT_ID);
CREATE INDEX IF NOT EXISTS IDX_JACKPOTS_PAYED_CREATED_DATE ON JACKPOTS (IS_PAYED, CREATED_DATE DESC);
