CREATE TABLE IF NOT EXISTS WITHDRAW_REQUESTS (
    ID BIGSERIAL PRIMARY KEY,
    CREATED_DATE TIMESTAMP,
    USER_CHAT_ID BIGINT NOT NULL,
    SUM BIGINT NOT NULL,
    PAYED_DATE TIMESTAMP,
    STATUS VARCHAR(64) NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_WITHDRAW_REQUESTS_USER_CHAT_ID ON WITHDRAW_REQUESTS (USER_CHAT_ID);
CREATE INDEX IF NOT EXISTS IDX_WITHDRAW_REQUESTS_STATUS_CREATED_DATE ON WITHDRAW_REQUESTS (STATUS, CREATED_DATE DESC);
