ALTER TABLE MATCHES
    ADD COLUMN IF NOT EXISTS TYPE VARCHAR(64) NOT NULL DEFAULT 'REGULAR';

ALTER TABLE MATCHES
    ADD COLUMN IF NOT EXISTS CREATOR_USER_CHAT_ID BIGINT;

ALTER TABLE MATCH_PLAYERS
    ADD COLUMN IF NOT EXISTS OWNER_USER_CHAT_ID BIGINT;
